-- MySQL Script generated by MySQL Workbench
-- Sat May  6 23:05:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hierarquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hierarquia` (
  `idHierarquia` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHierarquia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `hierarquia_idHierarquia` INT(11) NOT NULL,
  PRIMARY KEY (`idUser`, `hierarquia_idHierarquia`),
  INDEX `fk_user_hierarquia1_idx` (`hierarquia_idHierarquia` ASC),
  CONSTRAINT `fk_user_hierarquia1`
    FOREIGN KEY (`hierarquia_idHierarquia`)
    REFERENCES `mydb`.`hierarquia` (`idHierarquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gastos` (
  `idGastos` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `user_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idGastos`),
  INDEX `fk_gastos_user1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_gastos_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `idPagamentos` INT(11) NOT NULL AUTO_INCREMENT,
  `mesPagamento` VARCHAR(5) NOT NULL,
  `data` DATE NOT NULL,
  `user_idUser` INT(11) NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idPagamentos`),
  INDEX `fk_pagamentos_user_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_pagamentos_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
